########################################################################################
# "pnpm install" composite action using pnpm/action-setup@v4 with optimized caching #
#--------------------------------------------------------------------------------------#
# Uses the official pnpm action with Node.js cache integration for better performance #
# References:                                                                          #
#   - pnpm/action-setup: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time #
########################################################################################

name: "pnpm install"
description: "Run pnpm install with optimized caching using official pnpm action"

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
