########################################################################################
# "pnpm install" composite action using pnpm/action-setup@v4 with optimized caching #
#--------------------------------------------------------------------------------------#
# Uses the official pnpm action with Node.js cache integration for better performance #
# References:                                                                          #
#   - pnpm/action-setup: https://github.com/pnpm/action-setup#use-cache-to-reduce-installation-time #
########################################################################################

name: "pnpm install"
description: "Run pnpm install with optimized caching using official pnpm action"

inputs:
  node-version:
    description: "Node.js version to use (overrides .nvmrc)"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
      with:
        run_install: false

    - name: Install Node.js
      uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6
      with:
        node-version: ${{ inputs.node-version || '' }}
        node-version-file: ${{ inputs.node-version && '' || '.nvmrc' }}
        cache: 'pnpm'

    - name: Install dependencies
      shell: bash
      run: |
        pnpm install --frozen-lockfile
