name: Publish

on:
  release:
    types: [published]

permissions:
  contents: read
  id-token: write
  attestations: write

jobs:
  publish:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Enable corepack
        shell: bash
        run: corepack enable pnpm

      - name: Install dependencies
        uses: ./.github/actions/pnpm-nm-install

      - name: Setup npm registry
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          registry-url: https://registry.npmjs.org/

      - name: Lint
        run: pnpm lint

      - name: Run tests
        run: pnpm test:ci

      - name: Build package
        run: pnpm build

      - name: Generate build provenance attestation
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4
        with:
          subject-path: dist/**

      - name: Publish to npm with provenance
        run: pnpm publish --access public --no-git-checks --provenance

      - name: Publish to JSR
        run: pnpm dlx jsr publish
